In [1]:
import pandas as pd
import numpy as np
data_file=r"C:\Users\harya\Desktop\Edvancer\Python\Data\Data\SMSSpamCollection.txt"

In [2]:
sd=pd.read_csv(data_file,delimiter='\t',header=None,names=['target','message'])

In [3]:
sd.head()

target                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
lemma = WordNetLemmatizer()
stop = set(stopwords.words('english'))
# stop

In [6]:
def split_into_lemmas(message):
    message=message.lower()
    words = word_tokenize(message)
    words_sans_stop=[]
    for word in words :
        if word in stop:continue
        words_sans_stop.append(word)
    return [lemma.lemmatize(word) for word in words_sans_stop]

In [7]:
sd_train,sd_test=train_test_split(sd,test_size=0.2,random_state=2)

In [8]:
tfidf= TfidfVectorizer(analyzer=split_into_lemmas,min_df=20,max_df=3000)

In [9]:
tfidf.fit(sd_train['message'])

TfidfVectorizer(analyzer=<function split_into_lemmas at 0x0000025A4DAB9318>,
                binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=3000, max_features=None,
                min_df=20, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [10]:
train_data=tfidf.transform(sd_train['message'])

In [11]:
test_data=tfidf.transform(sd_test['message'])

In [12]:
clf=MultinomialNB()

In [13]:
clf.fit(train_data,sd_train['target'])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [14]:
clf.predict_proba(test_data[6,:])

array([[0.97932328, 0.02067672]])

In [15]:
clf.classes_

array(['ham', 'spam'], dtype='<U4')

In [16]:
list(sd_test['message'])[6]

'ELLO BABE U OK?'

## With Python pipeline

In [17]:
from sklearn.pipeline import Pipeline

Scikit-Learn pipelines are composed of steps, each of which has to be some kind of transformer except the last step which can be a transformer or an estimator such as a machine learning model. A few eg of transformers is Normalizer, StandardScaler or the One Hot Encoder to name a few.

In [18]:
pipe1=Pipeline(steps=[
    ('tfidf',TfidfVectorizer(analyzer=split_into_lemmas,min_df=20,max_df=3000)),
    ('classfier',MultinomialNB())
])

In [19]:
#Or you can also withe this way:
pipe1=Pipeline([
    ('tfidf',tfidf),
    ('classifier',clf)
])

In [20]:
pipe1.fit(sd_train['message'],sd_train['target'])

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer=<function split_into_lemmas at 0x0000025A4DAB9318>,
                                 binary=False, decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=3000, max_features=None,
                                 min_df=20, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('classifier',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbos

In [21]:
pipe1.predict_proba(sd_test['message'])

array([[0.95823681, 0.04176319],
       [0.99030404, 0.00969596],
       [0.99119974, 0.00880026],
       ...,
       [0.94020892, 0.05979108],
       [0.97748664, 0.02251336],
       [0.0141158 , 0.9858842 ]])

# Pipeline with Feature Union

In [22]:
class Human:
    def __init__(self,legs,arms):
        self.legs = legs
        self.arms = arms
#        legs = 2
#        arms = 2

In [23]:
bob = Human(2,2)
print(bob.legs)

#bob is the object. Human is the class
# A class is a blueprint or prototype that defines the variables and functions common to all objects,
# technically encapsulated together
# An objcet is a specimen of a class.
# Eg: Car is a class, maruti 800 is an object

#__init__ method is called constructot.
# IT is called as soon as the memory for the object is allocated.
# It sets attributes (or properties) on the object.
# self keyword which refers to the object.

2


In [24]:
file=r'C:\Users\harya\Desktop\Edvancer\Python\Data\Data\Existing Base.csv'

bd=pd.read_csv(file)

In [25]:
bd.head()

REF_NO children age_band                status        occupation  \
0       1     Zero    51-55               Partner     Manual Worker   
1       2     Zero    55-60  Single/Never Married           Retired   
2       3     Zero    26-30  Single/Never Married      Professional   
3       5     Zero    18-21  Single/Never Married      Professional   
4       6     Zero    45-50               Partner  Business Manager   

  occupation_partner home_status      family_income self_employed  \
0  Secretarial/Admin    Own Home  <17,500, >=15,000            No   
1            Retired    Own Home  <27,500, >=25,000            No   
2              Other    Own Home  <30,000, >=27,500           Yes   
3      Manual Worker    Own Home  <15,000, >=12,500            No   
4            Unknown    Own Home  <30,000, >=27,500            No   

  self_employed_partner  ...  Investment Tax Saving Bond Home Loan  \
0                    No  ...                       19.99      0.00   
1                    No  ...                        0.00      0.00   
2                    No  ...                        0.00      3.49   
3                    No  ...                        0.00      0.00   
4                    No  ...                        0.00     45.91   

  Online Purchase Amount Revenue Grid  gender         region  \
0                   0.00            1  Female          Wales   
1                   0.00            2  Female     North West   
2                   0.00            2    Male          North   
3                   0.00            2  Female  West Midlands   
4                  25.98            2  Female       Scotland   

   Investment in Commudity  Investment in Equity  Investment in Derivative  \
0                    74.67                 18.66                     32.32   
1                    20.19                  0.00                      4.33   
2                    98.06                 31.07                     80.96   
3                     4.10                 14.15                     17.57   
4                    70.16                 55.86                     80.44   

   Portfolio Balance  
0              89.43  
1              22.78  
2             171.78  
3             -41.70  
4             235.02  

[5 rows x 32 columns]

In [26]:
bd.nunique()

REF_NO                             10155
children                               5
age_band                              13
status                                 5
occupation                             9
occupation_partner                     9
home_status                            5
family_income                         13
self_employed                          2
self_employed_partner                  2
year_last_moved                       95
TVarea                                14
post_code                          10040
post_area                           2039
Average Credit Card Transaction     1411
Balance Transfer                    2183
Term Deposit                        1419
Life Insurance                      3111
Medical Insurance                   1589
Average A/C Balance                 2223
Personal Loan                       1760
Investment in Mutual Fund           2470
Investment Tax Saving Bond           832
Home Loan                            884
Online Purchase 

In [27]:
bd.dtypes

REF_NO                               int64
children                            object
age_band                            object
status                              object
occupation                          object
occupation_partner                  object
home_status                         object
family_income                       object
self_employed                       object
self_employed_partner               object
year_last_moved                      int64
TVarea                              object
post_code                           object
post_area                           object
Average Credit Card Transaction    float64
Balance Transfer                   float64
Term Deposit                       float64
Life Insurance                     float64
Medical Insurance                  float64
Average A/C Balance                float64
Personal Loan                      float64
Investment in Mutual Fund          float64
Investment Tax Saving Bond         float64
Home Loan  

In [28]:
from sklearn.base import BaseEstimator, TransformerMixin

In order for our custom transformer to be compatible with a scikit-learn pipeline it must be implemented as a class with methods such as fit, transorm, fit_transform, get_params, set_params. Instead of wititng all of those, we can simply just code the kind of transformation we want our transformer to apply and inherit everything else from some other class!

Below classes are the steps in the pipeline. They need to have 3 functions in them- init, fit and transform.

In [29]:
# This class will drop the columns whose names can be passed on the go
class VarTypeSelector(BaseEstimator, TransformerMixin):
    
    def __init__(self,vartype,ignore_var):
        self.vartype=vartype
        self.ignore_var=ignore_var
    
    def fit(self,x,y=None):
        return self
    
    def transform(self,X):
        return X.select_dtypes(self.vartype).drop(self.ignore_var,axis=1)

In [30]:
# This class will create dummies with n-1 values, and will ignore the categories where the
# count is less than some arbitrary value set by user.
class get_dummies_PipeLineFriendly(BaseEstimator, TransformerMixin):
    
    def __init__(self,freq_cutoff=0):
        self.freq_cutoff=freq_cutoff
        self.var_cat_dict={}
        
    def fit(self,x,y=None):
        data_cols=x.columns
        for col in data_cols:
            k=x[col].value_counts()
            cats=k.index[k>self.freq_cutoff][:-1]
            self.var_cat_dict[col]=cats
        return self
            
    def transform(self,x,y=None):
        dummy_data=x.copy()
        for col in self.var_cat_dict.keys():
            for cat in self.var_cat_dict[col]:
                name=col+'_'+cat
                dummy_data[name]=(dummy_data[col]==cat).astype(int)
            del dummy_data[col]
        return dummy_data

In [31]:
from sklearn.pipeline import Pipeline,FeatureUnion

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [33]:
bd_train,bd_test=train_test_split(bd,test_size=0.2,random_state=2)

In [34]:
x_train=bd_train.drop('Revenue Grid',axis=1)
x_test=bd_test.drop('Revenue Grid',axis=1)
y_train=bd_train['Revenue Grid']
y_test=bd_test['Revenue Grid']

In [35]:
bd.dtypes

REF_NO                               int64
children                            object
age_band                            object
status                              object
occupation                          object
occupation_partner                  object
home_status                         object
family_income                       object
self_employed                       object
self_employed_partner               object
year_last_moved                      int64
TVarea                              object
post_code                           object
post_area                           object
Average Credit Card Transaction    float64
Balance Transfer                   float64
Term Deposit                       float64
Life Insurance                     float64
Medical Insurance                  float64
Average A/C Balance                float64
Personal Loan                      float64
Investment in Mutual Fund          float64
Investment Tax Saving Bond         float64
Home Loan  

In [36]:
cat_pipe=Pipeline([
    ('cat_var',VarTypeSelector(['object'],ignore_var=['post_code','post_area'])),
    ('dummies',get_dummies_PipeLineFriendly(100))
])

In [37]:
#FeatureUnion class combines two or more pipeline objects.
# 1st pipeline is cat_pipe, 2nd is created in the combiner i.e. FeatureUnion itself

pipe2=Pipeline([
    ('features',FeatureUnion([
        ('cat_pipe',cat_pipe),
        ('num_var',VarTypeSelector(['int64','float64'],ignore_var=['REF_NO']))
    ])),
    ('clf',LogisticRegression())
])

In [38]:
# Calling the fir method for the feature union object pushes the data down 
# the piplines separately and then results are combined and returned.

pipe2.fit(x_train,y_train)

C:\Users\harya\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Pipeline(memory=None,
         steps=[('features',
                 FeatureUnion(n_jobs=None,
                              transformer_list=[('cat_pipe',
                                                 Pipeline(memory=None,
                                                          steps=[('cat_var',
                                                                  VarTypeSelector(ignore_var=['post_code',
                                                                                              'post_area'],
                                                                                  vartype=['object'])),
                                                                 ('dummies',
                                                                  get_dummies_PipeLineFriendly(freq_cutoff=100))],
                                                          verbose=False)),
                                                ('num_var',
                                                 Va

In [39]:
pipe2.predict_proba(x_test)

array([[0.00352334, 0.99647666],
       [0.00623159, 0.99376841],
       [0.00768033, 0.99231967],
       ...,
       [0.43372072, 0.56627928],
       [0.17600561, 0.82399439],
       [0.01433096, 0.98566904]])

## Save python objects to use later

In [40]:
from sklearn.externals import joblib

C:\Users\harya\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [41]:
joblib.dump(pipe1,'my_model_pipeline.pkl')

['my_model_pipeline.pkl']

## Loading models

In [1]:
import pandas as pd
from sklearn.externals import joblib
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stop = set(stopwords.words('english'))
from nltk.stem.wordnet import WordNetLemmatizer
lemma = WordNetLemmatizer()

C:\Users\harya\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
def split_into_lemmas(message):
    message=message.lower()
    words = word_tokenize(message)
    words_sans_stop=[]
    for word in words :
        if word in stop:continue
        words_sans_stop.append(word)
    return [lemma.lemmatize(word) for word in words_sans_stop]

In [3]:
mymodel=open('my_model_pipeline.pkl','rb')

In [4]:
pipe=joblib.load(mymodel)

In [5]:
my_msg=['I‘m going to try for 2 months ha ha only joking',
        '''Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. 
        Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's''']
my_df=pd.DataFrame({'message':my_msg})

In [6]:
my_df

message
0    I‘m going to try for 2 months ha ha only joking
1  Free entry in 2 a wkly comp to win FA Cup fina...

In [7]:
pipe.predict_proba(my_df['message'])

array([[0.95929988, 0.04070012],
       [0.01743449, 0.98256551]])

In [8]:
pipe.classes_

array(['ham', 'spam'], dtype='<U4')